cam_model: Pinhole
cam_width: 720
cam_height: 540
scale: 1.0
cam_fx: 351.6547241343154
cam_fy: 350.97590029372265
cam_cx: 342.91570997688115
cam_cy: 288.27050308689036
cam_d0: -0.03713375423447921
cam_d1: -0.007489770634057738
cam_d2: 0.003287983152377356
cam_d3: -0.0008136114053480689
