cam_3:
  cam_model: Pinhole
  cam_width: 720
  cam_height: 540
  scale: 1.0
  cam_fx: 355.585513023454
  cam_fy: 354.4708924377204
  cam_cx: 359.1699883054597
  cam_cy: 246.0908212151934
  cam_d0: -0.04738389395412899
  cam_d1: 0.006350363749183408
  cam_d2: -0.006374581267773348
  cam_d3: 0.0016867546434477334
