cam_1:
  cam_model: Pinhole  
  cam_width: 720
  cam_height: 540
  scale: 1.0
  cam_fx: 353.83530850045827
  cam_fy: 353.08084839605925
  cam_cx: 354.9603638484091
  cam_cy: 261.96623968254306
  cam_d0: -0.03908623683636908
  cam_d1: -0.008364734078508202
  cam_d2: 0.006865315014140142
  cam_d3: -0.0022325156415695015